# -*- coding: utf-8 -*-
"""Joining data.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1MvWD1dwExwKj4Mw-PcOsQIDqqlAekttK
"""

import pandas as pd

info = pd.read_csv("Info.csv")
doctor = pd.read_csv("doctor.csv")

combined1 = pd.merge(info,
                    doctor,
                    how="right",
                    on="P_ID")

combined1



differences = pd.merge(info, doctor, how='outer', indicator='Exist')
differences = differences.loc[differences['Exist'] != 'both']

differences

info.filter(['gender', 'height', 'weight']).head()